### ISSUE TITLE
Replace configuser with gpadmin user in packer scripts

### ISSUE THREAD

**Issue by cantzakas** [cantzakas/gpdb-packaging#14]
Discuss again security concerns but also consider _gpadmin_ is the "standard" user account used for connecting into the VM via SSH, start and stop the database, etc.

**Comment by davidje13** [comment]
gpadmin now has sudo privileges (but must enter their password), and the configuser has sudo privileges dropped at the end of the installation.

We made some attempt to delete the configuser entirely but packer's process makes this difficult.

gpadmin has been assigned a password of "changeme", which matches the default for other Greenplum tooling
